name = "delay-mirror"
main = "worker.js"
compatibility_date = "2024-09-23"

[vars]
DELAY_DAYS = "3"
NPM_REGISTRY = "https://registry.npmmirror.com"
NPM_DOWNLOAD_REGISTRY = "https://registry.npmjs.org"
GOMOD_REGISTRY = "https://goproxy.cn"
GOMOD_DOWNLOAD_REGISTRY = "https://goproxy.cn"
PYPI_SIMPLE_INDEX = "https://mirrors.aliyun.com/pypi/simple"
PYPI_JSON_API_BASE = "https://pypi.org/pypi"
PYPI_DOWNLOAD_BASE = "https://files.pythonhosted.org/packages"
PYPI_DOWNLOAD_MIRROR = "https://mirrors.aliyun.com/pypi/packages"
ALLOWLIST_ENABLED = "false"
